# Generated by Django 2.2.2 on 2019-06-14 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
