# Generated by Django 2.2.2 on 2019-06-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.CharField(default='github.com/johncervantes', max_length=200),
        ),
    ]
