# Generated by Django 2.2.2 on 2019-06-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_projects_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='github_link',
        ),
    ]
