# Generated by Django 2.2.2 on 2019-06-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_projects_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='summary',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
