# Generated by Django 2.2.2 on 2019-06-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_projects_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
