# Generated by Django 2.2.2 on 2019-06-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_projects_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='carousel',
            field=models.TextField(),
        ),
    ]
