# Generated by Django 2.2.2 on 2019-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190615_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='carousel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
